services:
  # WebSocket server for multiplayer
  - type: web
    name: poketactics-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && cd shared && npm run build && cd ../server && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production

staticSites:
  # Game client
  - name: poketactics-client
    buildCommand: npm install && npm run build
    publishDir: ./dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://poketactics-server-jjgo.onrender.com
